### ISSUE TITLE
mod_MLG.py errors with 1.0.2.2

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Main#3]
Hello,
For 1.0.2.2, there is an error with the MLG script, looks a quick fix

`2018-07-04 16:09:05.194: ERROR: Traceback (most recent call last):
2018-07-04 16:09:05.194: ERROR:   File "scripts/client/Avatar.py", line 2219, in updateArena
2018-07-04 16:09:05.194: ERROR:   File "scripts/client_common/ClientArena.py", line 312, in update
2018-07-04 16:09:05.194: ERROR:   File "mod_MLG.py", line 403, in new_onBasePointsUpdate
2018-07-04 16:09:05.194: ERROR: TypeError: py_logInfo argument tuple has invalid number of elements.`

It does not cause the client to crash, but after a 4 min training session there's about 150 of these (at least)

**Comment by Willster419** [comment]
P.S.
If you'd rather I post these in the forum topic, let me know :)

**Comment by Aimdrol** [comment]
Has been fixed with ffb15c6d3ef21e86ed78844e19535d62142613ac.

I actually prefer having the issues reported here. That way I do not have to manually add them to my to-do list. 😄
